fix nil pointer dereference
amir-the-h/okex pull request #7
Opened 2022-03-30 18:51 UTC by renat1015

calling the dial function sometimes returns a res (*http.Response) nil when the error is not nil

2022-03-30 19:17 UTC, amir-the-h requested changes
This is definitely not a rational way to handle the issue you mentioned in the description. If you think the 'res' is nil, you have to check for it instead of simply ignoring it.

2022-03-30 19:31 UTC, renat1015 commented
In this case, we are initializing the res variable to display the statusCode. The question of the rationality of adding a check of the res to nil, only for the conclusion is debatable. But the project is yours - and you decide!

If you decide so, I can fix it or you make the changes yourself. I use your library - and it's holding me up now(

2022-03-30 19:34 UTC, amir-the-h commented
I understand what you are saying. But that httpResponse will give us some good information on some points. I think it's better to have it and add some extra checks.

2022-03-30 19:53 UTC, renat1015 commented
I agree with you and fixed my commit!

2022-04-01 13:53 UTC, amir-the-h approved these changes

2022-04-01 13:53 UTC, merged